# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_system.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fml_system.proto\"\x12\n\x10HealthCheckInput\"#\n\x11HealthCheckOutout\x12\x0e\n\x06status\x18\x01 \x01(\t\"*\n\x11JobExecutionInput\x12\x15\n\rmodel_content\x18\x01 \x01(\t\"$\n\x12JobExecutionOutput\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1d\n\x0b\x41\x63tionInput\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\"9\n\x0c\x41\x63tionOutput\x12\x17\n\x0f\x61\x63knowledgement\x18\x01 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x02 \x01(\x0c\x32\xaf\x01\n\x08MlSystem\x12\x39\n\x0eHealthcheckReq\x12\x11.HealthCheckInput\x1a\x12.HealthCheckOutout\"\x00\x12*\n\tActionReq\x12\x0c.ActionInput\x1a\r.ActionOutput\"\x00\x12<\n\x0fJobExecutionReq\x12\x12.JobExecutionInput\x1a\x13.JobExecutionOutput\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEALTHCHECKINPUT']._serialized_start=19
  _globals['_HEALTHCHECKINPUT']._serialized_end=37
  _globals['_HEALTHCHECKOUTOUT']._serialized_start=39
  _globals['_HEALTHCHECKOUTOUT']._serialized_end=74
  _globals['_JOBEXECUTIONINPUT']._serialized_start=76
  _globals['_JOBEXECUTIONINPUT']._serialized_end=118
  _globals['_JOBEXECUTIONOUTPUT']._serialized_start=120
  _globals['_JOBEXECUTIONOUTPUT']._serialized_end=156
  _globals['_ACTIONINPUT']._serialized_start=158
  _globals['_ACTIONINPUT']._serialized_end=187
  _globals['_ACTIONOUTPUT']._serialized_start=189
  _globals['_ACTIONOUTPUT']._serialized_end=246
  _globals['_MLSYSTEM']._serialized_start=249
  _globals['_MLSYSTEM']._serialized_end=424
# @@protoc_insertion_point(module_scope)
